### ISSUE TITLE
Do some refactoring on the VSCode extension

### ISSUE THREAD

**Issue by JacobBovee** [xiaomi7732/StackBeauty#40]
With the new editor change the VSCode extension is starting to feel a bit cluttered. I'd like to get rid of the commands we're not using, maybe leaving the DateTime or disposable for testing purposes. I think the `extensions` file should be left purely for handling setup, actions, and commands - think of this as our "controller" and we should split the logic for the command actions into separate files. Nothing too complex for now just proposing a bit of tidying.

**Comment by xiaomi7732** [comment]
Addressed by #43.
